version: '3.4'

services:
  streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./app
    ports:
      - '8501:8501'
    volumes:
      - './app:/usr/src/app/:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    links:
      - redis
    depends_on:
      - redis
      - worker

  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - '6377:6379'

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - './worker:/usr/src/app/:delegated'