version: '3.4'

services:
  streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./app
    ports:
      - '8501:8501'
    volumes:
      - './app:/usr/src/app/:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    # container_name: rd01
    ports:
      - '6377:6379'

  producer:
    build:
      dockerfile: ./Dockerfile
      context: ./producer
    depends_on:
      - redis
    volumes:
      - './producer:/usr/src/app/:delegated'

  consumer:
    build:
      dockerfile: ./Dockerfile
      context: ./consumer
    depends_on:
      - redis
    volumes:
      - './consumer:/usr/src/app/:delegated'